/** Actions types */
export const ADD_CART = 'ADD_CART'
export const ORDER_CART = 'ORDER_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SELECT_PIZZA_TYPE = 'SELECT_PIZZA_TYPE'
export const SELECT_PIZZA_PROPS = 'SELECT_PIZZA_PROPS'
export const SELECT_PIZZA_PROPS_IN_CART = 'SELECT_PIZZA_PROPS_IN_CART'
export const CHANGE_PIZZA_COUNT_IN_CART = 'CHANGE_PIZZA_COUNT_IN_CART'