/** Actions types */
export const SELECT_PIZZA_TYPE = 'SELECT_PIZZA_TYPE'
export const SELECT_PIZZA_PROPS = 'SELECT_PIZZA_PROPS'
export const ADD_CART = 'ADD_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SELECT_PIZZA_PROPS_IN_CART = 'SELECT_PIZZA_PROPS_IN_CART'